nodeLinker: node-modules

packageExtensions:
  "media-chrome@*":
    peerDependencies:
      react: "*"
  "@mux/mux-player@*":
    peerDependencies:
      react: "*"
  "player.style@*":
    peerDependencies:
      react: "*"
